source 'https://github.com/CocoaPods/Specs.git'

target 'MTLFMDBAdapter', :exclusive => true do
  pod "MTLFMDBAdapter", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MTLFMDBAdapter", :path => "../"

  pod 'Specta', '0.5.0'
  pod 'Expecta'
#  pod 'FBSnapshotTestCase'
  #pod 'Expecta+Snapshots'
end
