source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MTLFMDBAdapter' do
    platform :ios, '8.0'
  pod 'MTLFMDBAdapter', :path => "../"
  
  target 'Tests' do
      inherit! :search_paths
      pod 'Specta', '~> 1.0'
      pod 'Expecta', '~> 1.0'
      #pod 'FBSnapshotTestCase'
      #pod 'Expecta+Snapshots'
    end
end

